
spring:
  application:
    name: springcloud-consumer-hystrix

server:
  port: 9706

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://abc:abc@localhost:8761/eureka


feign:
  hystrix:
    enabled: true
        