spring:
  security:
    user:
      name: abc
      password: abc
        
        
server:
  port: 8761
#  context-path: /eureka
eureka:
  instance:
    hostname: localhost
  client:
    # 以下两项一定要是false，表明自己是服务器，而不需要从其他主机发现服务
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/


        